version: '3.8'
services:
  mynotes:
    build: .
    container_name: mynotes-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - ADMIN_PASSWORD=123456
      - DAV_USER=坚果云邮箱
      - DAV_PASSWORD=坚果云密码
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
